import React, { createContext, useState } from "react";
export const Storedata = createContext();

function Store(props) {
  const [data, setdata] = useState([
    //   mobile phones

    // under 10k
    {
      id: "1",
      name: "realme C51 (Mint Green, 64 GB)",
      image: "https://i.postimg.cc/4xrnY7wy/original-imagt4qptrkzwmxa.webp",
      price: "8,999",
      cross: "10,999",
      stars: 4.4,
      review: "43,827",
      off: "18",
      type: "under10k",
    },
    {
      id: "2",
      name: "REDMI 12 (Jade Black, 128 GB)",
      image: "https://i.postimg.cc/xTLG61DD/REDMI-12-Jade-Black-128-GB.webp",
      price: "9,499",
      cross: "14,999",
      stars: 4.3,
      review: "72,852",
      type: "under10k",
      off: "37",
    },
    {
      id: "3",
      name: "POCO C55 (Forest Green, 128 GB) ",
      image: {
        img1: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/a/6/f/-original-imagnb6nvnqz7hqq.jpeg?q=70",

        img2: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/g/n/q/-original-imagnb6npf9gmjzq.jpeg?q=70",
        img3: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/c/u/e/-original-imagnb6nw6gmqzxe.jpeg?q=70",
        img4: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/7/w/k/-original-imagnb6na9tyebbg.jpeg?q=70",
        img5: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/m/t/p/-original-imagnb6nhzjt3fuj.jpeg?q=70",
      },
      price: "7,999",
      cross: "13,999",
      stars: 4.2,
      review: "82,871",
      type: "under10k",
      bestof: "mobileallbest",
      off: "42",
      dec: "The POCO C55 smartphone features a powerful MediaTek Helio G85 processor with 1 GHz of GPU enabling you with a smooth and hassle-free gaming experience or multitasking. This smartphone’s leather-like texture with stitches on the panel gives it a classy look. The 50 MP dual camera featured in this smartphone has a night mode and HDR mode so you can capture life-like images. You can also enjoy long-lasting battery life with the 5000 mAh battery.",
    },
    {
      id: "4",
      name: "I Kall S1 Plus (Golden, 128 GB) ",
      image: "https://i.postimg.cc/fRy0dzKh/I-Kall-S1-Plus-Golden-128-GB.webp",
      price: "9,489",
      cross: "11,999",
      stars: 3.5,
      review: "205",
      type: "under10k",
      off: "21",
    },
    {
      id: "5",
      name: "REDMI 12 (Pastel Blue, 128 GB) ",
      image: "https://i.postimg.cc/V6WjR7by/REDMI-12-Pastel-Blue-128-GB.webp",
      price: "9,499",
      cross: "14,999",
      stars: 4.3,
      review: "72,887",
      type: "under10k",
      off: "36",
    },
    {
      id: "6",
      name: "realme C51 (Carbon Black, 64 GB)",
      image: "https://i.postimg.cc/25ZpVWLL/realme-C51-Carbon-Black-64-GB.webp",
      price: "8,999",
      cross: "10,999",
      stars: 4.4,
      review: "44,853",
      type: "under10k",
      off: "18",
    },

    // under 10-20k
    {
      id: "7",
      name: "realme C53 (Champion Gold, 128 GB) ",
      image:
        "https://i.postimg.cc/zvMFQx8x/realme-C53-Champion-Gold-128-GB.webp",
      price: "11,999",
      cross: "13,999",
      stars: 4.4,
      review: "72,256",
      type: "under10-20k",
      off: "14",
    },
    {
      id: "8",
      name: "POCO M6 Pro 5G (Power Black, 128 GB) ",
      image:
        "https://i.postimg.cc/QxkjDCFJ/POCO-M6-Pro-5-G-Power-Black-128-GB.webp",
      price: "12,249",
      cross: "14,999",
      stars: 4.3,
      review: "43,038",
      type: "under10-20k",
      off: "18",
    },

    {
      id: "9",
      name: "realme 11x 5G (Purple Dawn, 128 GB)",

      image: {
        img1: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/e/q/g/-original-imagtqqd4vcdzqdg.jpeg?q=70",

        img2: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/e/x/p/-original-imagtqqds9nzjhaz.jpeg?q=70",
        img3: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/j/7/-original-imagtqqdzsbzybr5.jpeg?q=70",
        img4: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/a/k/u/-original-imagtqqddayaekur.jpeg?q=70",
        img5: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/0/p/i/-original-imagtqqddy77nsq2.jpeg?q=70",
      },
      price: "14,999",
      cross: "16,999",
      stars: 4.4,
      review: "80,436",
      type: "under10-20k",
      bestof: "mobileallbest",
      off: "12",
    },

    {
      id: "10",
      name: "vivo T2x 5G (Aurora Gold, 128 GB) ",
      image: {
        img1: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/c/s/x/-original-imagzjhwaaewgj8r.jpeg?q=70",

        img2: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/g/j/x/-original-imagzjhwyujd6mzy.jpeg?q=70",
        img3: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/o/7/4/-original-imagzjhwge3gzsmb.jpeg?q=70",
        img4: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/v/p/q/-original-imagzjhwkgvefqrm.jpeg?q=70",
        img5: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/0/p/i/-original-imagtqqddy77nsq2.jpeg?q=70",
      },
      price: "12,999",
      cross: "18,999",
      stars: 4.2,
      review: "2,45,876",
      type: "under10-20k",
      bestof: "mobileallbest",
      off: "32",
    },

    {
      id: "11",
      name: "SAMSUNG Galaxy F14 5G (OMG Black, 128 GB) ",
      image:
        "https://i.postimg.cc/CL90g8Nt/SAMSUNG-Galaxy-F14-5-G-OMG-Black-128-GB.webp",
      price: "14,990",
      cross: "18,599",
      stars: 4.2,
      review: "67,639",
      type: "under10-20k",
      off: "20",
    },

    {
      id: "12",
      name: "OnePlus Nord CE 2 Lite 5G (Black Dusk, 128 GB)",
      image: {
        img1: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/2/p/8/-original-imagg2a4rmk94gay.jpeg?q=70",

        img2: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/p/e/h/-original-imagg2a49gm7qx5c.jpeg?q=70",
        img3: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/c/i/e/-original-imagm27ghg9hz8zw.jpeg?q=70",
        img4: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/a/v/3/-original-imagg2a4t7jhf34p.jpeg?q=70",
        img5: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/u/i/o/-original-imagg2a4nuq8yjmf.jpeg?q=70",
      },

      price: "16,971",
      cross: "19,999",
      stars: 4.6,
      review: "1,34,539",
      type: "under10-20k",
      bestof: "mobileallbest",
      featureproduct: "allbest",
      off: "15",
    },

    // Premium Mobiles above ₹20,000+
    {
      id: "13",
      name: "realme 11 Pro 5G (Oasis Green, 128 GB)",
      image:
        "https://i.postimg.cc/sggtMdPt/realme-11-Pro-5-G-Oasis-Green-128-GB.webp",
      price: "23,999",
      cross: "25,999",
      stars: 4.6,
      review: "69,403",
      type: "above20k",
      off: "8",
    },
    {
      id: "14",
      name: "OnePlus Nord CE 3 Lite 5G (Pastel Lime, 256 GB)  ",
      image:
        "https://i.postimg.cc/t4KPJ68w/One-Plus-Nord-CE-3-Lite-5-G-Pastel-Lime-256-GB.webp",
      price: "21,899",
      cross: "24,999",
      stars: 4,
      review: "24,539",
      type: "above20k",
      off: "13",
    },
    {
      id: "15",
      name: "OPPO Reno10 5G (Silvery Grey, 256 GB)  ",
      image:
        "https://i.postimg.cc/dDMk3Pxd/OPPO-Reno10-5-G-Silvery-Grey-256-GB.webp",
      price: "32,999",
      cross: "38,999",
      stars: 4.2,
      review: "33,347",
      type: "above20k",
      off: "16",
    },
    {
      id: "16",
      name: "APPLE iPhone 12 (White, 64 GB)",
      image: "https://i.postimg.cc/FFCwqFM1/APPLE-i-Phone-12-White-64-GB.webp",
      price: "41,999",
      cross: "49,999",
      stars: 4.6,
      review: "2,03,739",
      type: "above20k",
      off: "17",
    },
    {
      id: "17",
      name: "vivo V29 5G (Red, 256 GB) ",
      image: "https://i.postimg.cc/FKBGs1NB/vivo-V29-5-G-Red-256-GB.webp",
      price: "36,999",
      cross: "39,999",
      stars: 4.1,
      review: "539",
      type: "above20k",
      featureproduct: "allbest",
      off: "8",
    },
    {
      id: "18",
      name: "APPLE iPhone 14 (Purple, 128 GB)",
      image: {
        img1: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/b/u/f/-original-imaghxa5hvapbfds.jpeg?q=70",

        img2: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/q/m/2/-original-imaghxcp4sfjxhva.jpeg?q=70",
        img3: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/5/i/7/-original-imaguypzzhbzm5an.jpeg?q=70",
        img4: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/1/d/y/-original-imaghxcpvtta2hzs.jpeg?q=70",
        img5: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/q/b/i/-original-imaghxcptg5mdycw.jpeg?q=70",
      },

      price: "61,999",
      cross: "69,999",
      stars: 4.6,
      review: "2,54,139",
      type: "above20k",
      bestof: "mobileallbest",
      off: "12",
    },

    // realme phones
    {
      id: "19",
      name: "realme C51 (Carbon Black, 64 GB)",
      image: "https://i.postimg.cc/25ZpVWLL/realme-C51-Carbon-Black-64-GB.webp",
      price: "8,999",
      cross: "10,999",
      stars: 4.4,
      review: "44,853",
      type: "realme",
      off: "19",
    },
    {
      id: "20",
      name: "realme C53 (Champion Gold, 128 GB) ",
      image:
        "https://i.postimg.cc/zvMFQx8x/realme-C53-Champion-Gold-128-GB.webp",
      price: "11,999",
      cross: "13,999",
      stars: 4.4,
      review: "72,256",
      type: "realme",
      off: "15",
    },
    {
      id: "21",
      name: "realme Narzo 60x 5G (Stellar Green, 128 GB)",
      image:
        "https://i.postimg.cc/FK3vxzNk/realme-Narzo-60x-5-G-Stellar-Green-128-GB.webp",
      price: "13,850",
      cross: "25,999",
      stars: 4.1,
      review: "403",
      type: "realme",
      off: "47",
    },
    {
      id: "22",
      name: "realme 11x 5G (Purple Dawn, 128 GB)",
      image: {
        img1: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/b/u/f/-original-imaghxa5hvapbfds.jpeg?q=70",

        img2: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/q/m/2/-original-imaghxcp4sfjxhva.jpeg?q=70",
        img3: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/5/i/7/-original-imaguypzzhbzm5an.jpeg?q=70",
        img4: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/1/d/y/-original-imaghxcpvtta2hzs.jpeg?q=70",
        img5: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/q/b/i/-original-imaghxcptg5mdycw.jpeg?q=70",
      },

      price: "14,999",
      cross: "16,999",
      stars: 4.4,
      review: "80,436",
      type: "realme",

      off: "12",
    },

    {
      id: "23",
      name: "realme 11 Pro 5G (Oasis Green, 128 GB)",
      image:
        "https://i.postimg.cc/sggtMdPt/realme-11-Pro-5-G-Oasis-Green-128-GB.webp",
      price: "23,999",
      cross: "25,999",
      stars: 4.6,
      review: "69,403",
      type: "realme",
      off: "8",
    },

    {
      id: "24",
      name: "realme GT 2 Pro (Paper White, 256 GB)",
      image:
        "https://i.postimg.cc/tgL9Wcfk/realme-GT-2-Pro-Paper-White-256-GB.webp",
      price: "34,999",
      cross: "44,999",
      stars: 4.1,
      review: "5,403",
      type: "realme",
      featureproduct: "allbest",
      off: "23",
    },
    // samsung

    {
      id: "25",
      name: " SAMSUNG Galaxy M14 5G (Berry Blue, 128 GB) ",
      image:
        "https://i.postimg.cc/jjNrJw39/SAMSUNG-Galaxy-M14-5-G-Berry-Blue-128-GB.webp",
      price: "12,599",
      cross: "17,999",
      stars: 4.2,
      review: "2,103",
      type: "samsung",
      off: "31",
    },
    {
      id: "26",
      name: " SAMSUNG Galaxy A14 5G (Light Green, 128 GB) ",
      image:
        "https://i.postimg.cc/7YFNB5Zw/SAMSUNG-Galaxy-A14-5-G-Light-Green-128-GB.webp",
      price: "17,999",
      cross: "20,999",
      stars: 4.1,
      review: "8,640",
      type: "samsung",
      off: "15",
    },
    {
      id: "27",
      name: " SAMSUNG Galaxy A23 5G (Light Blue, 128 GB)  ",
      image: {
        img1: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/e/d/r/-original-imagmym54wrhzgpn.jpeg?q=70",

        img2: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/b/a/2/-original-imagmym5myfw4dpu.jpeg?q=70",
        img3: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/a/o/p/-original-imagmym5ffugfert.jpeg?q=70",
        img4: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/9/y/f/-original-imagmym58bzdw6t8.jpeg?q=70",
        img5: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/c/t/s/-original-imagmym5rgsaaeau.jpeg?q=70",
      },

      price: "21,999",
      cross: "28,999",
      stars: 4.1,
      review: "1,600",
      type: "samsung",
      off: "25",
      bestof: "mobileallbest",
    },
    {
      id: "28",
      name: "SAMSUNG Galaxy A34 5G (Awesome Violet, 256 GB)",
      image:
        "https://i.postimg.cc/bvyDwPwK/SAMSUNG-Galaxy-A34-5-G-Awesome-Violet-256-GB.webp",
      price: "31,999",
      cross: "49,999",
      stars: 4.2,
      review: "4,683",
      type: "samsung",
      featureproduct: "allbest",
      off: "37",
    },
    {
      id: "29",
      name: " SAMSUNG Galaxy Z Flip3 5G (Cream, 128 GB)  (8 GB RAM)",
      image:
        "https://i.postimg.cc/3NXnmGPL/SAMSUNG-Galaxy-Z-Flip3-5-G-Cream-128-GB-8-GB-RAM.webp",
      price: "49,999",
      cross: "59,999",
      stars: 4.3,
      review: "6,832",
      type: "samsung",
      off: "17",
    },
    {
      id: "30",
      name: " SAMSUNG Galaxy S23 Ultra 5G (Phantom Black, 256 GB) ",
      image:
        "https://i.postimg.cc/wBBqrc2m/SAMSUNG-Galaxy-S23-Ultra-5-G-Phantom-Black-256-GB.webp",
      price: "1,24,999",
      cross: "1,49,999",
      stars: 4.1,
      review: "7,503",
      type: "samsung",
      off: "17",
    },

    // iphone
    {
      id: "31",
      name: "Apple iPhone SE (White, 256 GB)",
      image: "https://i.postimg.cc/tT0vjBdM/Apple-i-Phone-SE-White-256-GB.webp",
      price: "40,999",
      cross: "55,999",
      stars: 4.5,
      review: "1,54,764",
      type: "iphone",
      off: "27",
    },
    {
      id: "32",
      name: "APPLE iPhone 12 (White, 64 GB)",
      image: "https://i.postimg.cc/FFCwqFM1/APPLE-i-Phone-12-White-64-GB.webp",
      price: "41,999",
      cross: "49,999",
      stars: 4.6,
      review: "2,03,739",
      type: "iphone",
      featureproduct: "allbest",
      off: "17",
    },
    {
      id: "33",
      name: "APPLE iPhone 14 (Purple, 128 GB)",
      image:
        "https://i.postimg.cc/PrxvXyV2/APPLE-i-Phone-14-Purple-128-GB.webp",
      price: "61,999",
      cross: "69,999",
      stars: 4.6,
      review: "2,54,139",
      type: "iphone",
      off: "12",
    },
    {
      id: "34",
      name: " APPLE iPhone 13 (Blue, 128 GB)",
      image: "https://i.postimg.cc/pdyZL4kX/APPLE-i-Phone-13-Blue-128-GB.webp",
      price: "59,900",
      cross: "69,999",
      stars: 4.7,
      review: "2,70,403",
      type: "iphone",
      off: "15",
    },
    {
      id: "35",
      name: " APPLE iPhone 11 (Black, 64 GB)",
      image: "https://i.postimg.cc/PrsTzk89/APPLE-i-Phone-11-Black-64-GB.webp",
      price: "43,999",
      cross: "49,999",
      stars: 4.3,
      review: "2,23,503",
      type: "iphone",
      off: "13",
    },

    {
      id: "36",
      name: " APPLE iPhone 15 Plus (Pink, 512 GB)",
      image:
        "https://i.postimg.cc/KYcwFm1K/APPLE-i-Phone-15-Plus-Pink-512-GB.webp",
      price: "1,19,999",
      cross: "1,39,999",
      stars: 4.7,
      review: "12,503",
      type: "iphone",
      featureproduct: "allbest",
      off: "15",
    },

    // Electronices

    // mobile accessorise

    {
      id: "37",
      name: "    Mi Fast USB Type C 22.5W charger combo for Mobiles with detachable USB cable(White, Cable Included)",
      image:
        "https://i.postimg.cc/7Y5rNWLF/Mi-Fast-USB-Type-C-22-5-W-charger-combo-for-Mobiles-with-detachable-USB-cable-White-Cable-Included.webp",
      price: "699",
      cross: "999",
      stars: 4.3,
      review: "16,103",
      type: "mobile-accessorise",
      off: "31",
    },
    {
      id: "38",
      name: "boAt 20 W PD 5 A Mobile Charger  (White)",
      image:
        "https://i.postimg.cc/t4XPfw1g/bo-At-20-W-PD-5-A-Mobile-Charger-White.webp",
      price: "445",
      cross: "999",
      stars: 4.1,
      review: "1,503",
      type: "mobile-accessorise",
      off: "56",
    },
    {
      id: "39",
      name: "RAEGR RG10340 Arc 750 Charging Stand 15W -C",
      image:
        "https://i.postimg.cc/3RC0nZKG/RAEGR-RG10340-Arc-750-Charging-Stand-15-W-C.webp",
      price: "1,999",
      cross: "3,999",
      stars: 3.3,
      review: "103",
      type: "mobile-accessorise",
      off: "51",
    },
    {
      id: "40",
      name: "MAK 80 W SuperVOOC 6 A Mobile Charger  (White)",
      image:
        "https://i.postimg.cc/pLsHY5bd/MAK-80-W-Super-VOOC-6-A-Mobile-Charger-White.webp",
      price: "459",
      cross: "1,999",
      stars: 4.5,
      review: "6,453",
      type: "mobile-accessorise",
      off: "77",
    },
    {
      id: "41",
      name: "VIGGO 65 W SuperVOOC 6 A Mobile Charger with Detachable Cable",
      image:
        "https://i.postimg.cc/sX6Qkghf/char06-covj-original-imagefuwmqeauynk.webp",
      price: "499",
      cross: "1,999",
      stars: 3.3,
      review: "253",
      type: "mobile-accessorise",
      off: "75",
    },
    {
      id: "42",
      name: "RAEGR RG10121_MII Arc 400 Pro 15W Type-C PD  Charging Pad.webp",
      image:
        "https://i.postimg.cc/43tTCLHY/RAEGR-RG10121-MII-Arc-400-Pro-15-W-Type-C-PD-Charging-Pad.webp",
      price: "799",
      cross: "2,999",
      stars: 3.2,
      review: "208",
      type: "mobile-accessorise",
      off: "73",
    },
    // it accessorise
    {
      id: "43",
      name: "Kreo Hive RGB Gaming Mechanical Keyboard, RGB Keyboards,Wired USB Gaming Keyboard",
      image:
        "https://i.postimg.cc/ZRGGwr5r/Kreo-Hive-RGB-Gaming-Mechanical-Keyboard-RGB-Keyboards-Braided-Cable-Led-Keyboard-Wired-USB-Gamin.webp",
      price: "2,999",
      cross: "4,599",
      stars: 4.1,
      review: "343",
      type: "it-accessorise",
      off: "34",
    },
    {
      id: "44",
      name: "HP K160 Wireless Desktop Keyboard  (Black)",
      image:
        "https://i.postimg.cc/7ZJgk0HC/HP-K160-Wireless-Desktop-Keyboard-Black.webp",
      price: "899",
      cross: "1,699",
      stars: 4.3,
      review: "753",
      type: "it-accessorise",
      off: "47",
    },
    {
      id: "45",
      name: "TP-Link Archer c60(us) 1350 Mbps Wireless Router  (White, Dual Band)",
      image:
        "https://i.postimg.cc/jSktznPh/TP-Link-Archer-c60-us-1350-Mbps-Wireless-Router-White-Dual-Band.webp",
      price: "2,799",
      cross: "3,999",
      stars: 4,
      review: "8,248",
      type: "it-accessorise",
      off: "30",
    },
    {
      id: "46",
      name: "RAKSHIT Electronics FI JMR 541 Pocket WiFi 150 Mbps 4G Router  ",
      image:
        "https://i.postimg.cc/dQ7H1kVY/RAKSHIT-Electronics-FI-JMR-541-Pocket-Wi-Fi-150-Mbps-4-G-Router.webp",
      price: "2,499",
      cross: "6,999",
      stars: 3.7,
      review: "143",
      type: "it-accessorise",
      off: "64",
    },
    {
      id: "47",
      name: "WACOM CTL-6100WL/K0-CX INTUOS SMALL 5.3 x 8.5 inch Graphics Tablet(Black, Connectivity-Bluetooth, USB)",
      image: {
        img1: "https://rukminim2.flixcart.com/image/416/416/jiulk7k0/graphics-tablet/2/c/x/intuos-small-medium-no-ctl-6100wl-k0-cx-wacom-original-imaf6jy4d3afk3g3.jpeg?q=70",

        img2: "https://rukminim2.flixcart.com/image/416/416/jiulk7k0/graphics-tablet/2/c/x/intuos-small-medium-no-ctl-6100wl-k0-cx-wacom-original-imaf6jy4zf6s4vfu.jpeg?q=70",
        img3: "https://rukminim2.flixcart.com/image/416/416/jiulk7k0/graphics-tablet/2/c/x/intuos-small-medium-no-ctl-6100wl-k0-cx-wacom-original-imaf6jy4geaeqfyc.jpeg?q=70",
        img4: "https://rukminim2.flixcart.com/image/416/416/jiulk7k0/graphics-tablet/2/c/x/intuos-small-medium-no-ctl-6100wl-k0-cx-wacom-original-imaf6jy4cyzhjyte.jpeg?q=70",
        img5: "https://rukminim2.flixcart.com/image/416/416/jiulk7k0/graphics-tablet/2/c/x/intuos-small-medium-no-ctl-6100wl-k0-cx-wacom-original-imaf6jy4kz98sku5.jpeg?q=70",
      },
      price: "11,999",
      cross: "16,599",
      stars: 4.3,
      review: "283",
      type: "it-accessorise",
      bestof: "itallbest",
      off: "28",
    },
    {
      id: "48",
      name: "Kreo Hawk Wired Gaming Mouse, Pixart Sensor, RGB Mouse, Adjustable DPI upto 12400 Wired Optical Gaming Mouse  (USB 2.0, Black)",
      image:
        "https://i.postimg.cc/bvNq7cf3/Kreo-Hawk-Wired-Gaming-Mouse-Pixart-Sensor-RGB-Mouse-Adjustable-DPI-upto-12400-Wired-Optical-Gami.webp",
      price: "1,349",
      cross: "2,999",
      stars: 4.6,
      review: "453",
      type: "it-accessorise",
      off: "55",
    },

    // laptop

    {
      id: "49",
      name: "ASUS Vivobook 15 Core i5 11th Gen 1135G7 - (8 GB/512 GB SSD/Windows 11 Home) X515EA-EJ522WS Thin and Light Laptop  (15.6 Inch, Transparent Silver, 1.80 kg, With MS Office)",
      image:
        "https://i.postimg.cc/KzQKLrr8/ASUS-Vivobook-15-Core-i5-11th-Gen-1135-G7.webp",
      price: "43,999",
      cross: "55,699",
      stars: 4.3,
      review: "6,353",
      type: "laptop",
      off: "21",
    },
    {
      id: "50",
      name: "Lenovo IdeaPad Gaming 3 Intel Core i5 11th Gen 11300H - (8 GB/512 GB SSD/Windows 11 Home/4 GB Graphics/NVIDIA GeForce GTX 1650/120 Hz) 15IHU6 Gaming Laptop  (15.6 Inch, Shadow Black, 2.25 kg)",
      image: {
        img1: "https://rukminim2.flixcart.com/image/416/416/xif0q/computer/n/n/q/-original-imagu3kmvtfdy5hk.jpeg?q=70",

        img2: "https://rukminim2.flixcart.com/image/416/416/xif0q/computer/d/1/y/-original-imagu7n9kya6nkp6.jpeg?q=70",
        img3: "https://rukminim2.flixcart.com/image/416/416/xif0q/computer/l/f/m/gaming-3-gaming-laptop-lenovo-original-imaghtkrz5zzrvkh.jpeg?q=70",
        img4: "https://rukminim2.flixcart.com/image/416/416/xif0q/computer/i/b/a/-original-imagw5u3g22knnqr.jpeg?q=70",
        img5: "https://rukminim2.flixcart.com/image/416/416/xif0q/computer/l/d/f/gaming-3-gaming-laptop-lenovo-original-imaghtkr8py2usjm.jpeg?q=70",
      },

      price: "45,999",
      cross: "67,699",
      stars: 4.3,
      review: "4,953",
      type: "laptop",
      bestof: "itallbest",
      off: "32",
    },
    {
      id: "51",
      name: "MSI GF63 Core i5 11th Gen 11260H - (8 GB/512 GB SSD/Windows 11 Home/4 GB Graphics/NVIDIA GeForce GTX 1650/60 Hz) GF63 Thin 11SC-1494IN Gaming Laptop  (15.6 Inch, Black, 1.86 Kg)",
      image:
        "https://i.postimg.cc/QM3vPvvV/MSI-GF63-Core-i5-11th-Gen-11260-H.webp",
      price: "47,999",
      cross: "69,699",
      stars: 4.3,
      review: "953",
      type: "laptop",
      off: "31",
    },
    {
      id: "52",
      name: "ASUS Vivobook Pro 15 For Creator, Ryzen 5 Hexa Core 5600HS - (8 GB/512 GB SSD/Windows 11 Home/4 GB Graphics/NVIDIA GeForce RTX 2050) M6500QF-HN521W Gaming Laptop  (15.6 Inch, Quiet Blue, 1.80 Kg)",
      image: {
        img1: "https://rukminim2.flixcart.com/image/416/416/xif0q/computer/e/k/d/asus-vivobook-pro-15-creator-laptop-asus-original-imagvggwgnu3b7kz.jpeg?q=70",

        img2: "https://rukminim2.flixcart.com/image/416/416/xif0q/computer/2/e/s/asus-vivobook-pro-15-creator-laptop-asus-original-imagvggwbb3gwwkd.jpeg?q=70",
        img3: "https://rukminim2.flixcart.com/image/416/416/xif0q/computer/q/p/k/asus-vivobook-pro-15-creator-laptop-asus-original-imagvggwrqhxgkhu.jpeg?q=70",
        img4: "https://rukminim2.flixcart.com/image/416/416/xif0q/computer/u/y/f/asus-vivobook-pro-15-creator-laptop-asus-original-imagvggwjfh9hkt3.jpeg?q=70",
        img5: "https://rukminim2.flixcart.com/image/416/416/xif0q/computer/l/b/y/asus-vivobook-pro-15-creator-laptop-asus-original-imagvggwzshggpfq.jpeg?q=70",
      },

      price: "49,999",
      cross: "71,699",
      stars: 4.3,
      review: "9,433",
      type: "laptop",
      bestof: "itallbest",
      off: "30",
    },
    {
      id: "53",
      name: "HP Victus Ryzen 5 Hexa Core 5600H - (8 GB/512 GB SSD/Windows 11 Home/4 GB Graphics/AMD Radeon RX 6500M/60 Hz) 15-fb0147AX Gaming Laptop  (15.6 Inch, Performance Blue, 2.37 Kg)",
      image:
        "https://i.postimg.cc/qqq87M6q/HP-Victus-Ryzen-5-Hexa-Core-5600-H.webp",
      price: "51,099",
      cross: "63,699",
      stars: 4.1,
      review: "1,853",
      type: "laptop",
      off: "20",
    },
    {
      id: "54",
      name: "ASUS TUF Gaming F15 - AI Powered Gaming Core i5 11th Gen 11260H - (8 GB/512 GB SSD/Windows 11 Home/4 GB Graphics/NVIDIA GeForce RTX 2050/144 Hz/70 W) FX506HF-HN075W Gaming Laptop  (15.6 Inch, Graphite Black, 2.30 kg)",
      image:
        "https://i.postimg.cc/dtkVPq25/tuff-gaming-laptop-asus-original-imag9vzdu9ksdfzy.webp",
      price: "53,599",
      cross: "78,999",
      stars: 4.2,
      review: "2,913",
      type: "laptop",
      off: "32",
    },

    // shoes
    // sneakers
    {
      id: "55",
      name: " Solethreads RebelSneakers For Men  (Khaki)",
      image: "https://i.postimg.cc/HWbTBJ39/Sneakers-For-Men-Khaki.webp",
      price: "1,799",
      cross: "2,999",
      stars: 4,
      review: "229",
      type: "sneakers",
      bestof: "shoesallbest",
      off: "40",
    },
    {
      id: "56",
      name: "Sparx SM-641 Sneakers For Men  (Green, Yellow)",
      image:
        "https://i.postimg.cc/Y2ZVvkFG/SM-641-Sneakers-For-Men-Green-Yellow.webp",
      price: "1,759",
      cross: "2,899",
      stars: 4.3,
      review: "3,872",
      type: "sneakers",
      bestof: "shoesallbest",
      off: "41",
    },
    {
      id: "57",
      name: "Adidas Sneakers For Men  (White)",
      image:
        "https://i.postimg.cc/L52MgTcQ/GRAND-COURT-TD-Sneakers-For-Men-White.webp",
      price: "3,299",
      cross: "6,999",
      stars: 4.3,
      review: "739",
      type: "sneakers",
      bestof: "shoesallbest",
      off: "52",
    },
    {
      id: "58",
      name: "Sparx SM-671 Sneakers For Men  (Black)",
      image: "https://i.postimg.cc/h4m3mTMc/SM-671-Sneakers-For-Men-Black.webp",
      price: "1,100",
      cross: "1,299",
      stars: 4.1,
      review: "7,139",
      type: "sneakers",
      bestof: "shoesallbest",
      off: "15",
    },
    {
      id: "59",
      name: "New Balance 327 Sneakers For Men  (Multicolor)",
      image:
        "https://i.postimg.cc/jqFX55yP/327-Sneakers-For-Men-Multicolor.webp",
      price: "5,200",
      cross: "10,599",
      stars: 4.6,
      review: "2,439",
      type: "sneakers",
      bestof: "shoesallbest",
      off: "50",
    },
    {
      id: "60",
      name: "Skechers Sneakers For Men  (Black)",
      image:
        "https://i.postimg.cc/25FS3VJw/SUMMITS-TORRE-Sneakers-For-Men-Black.webp",
      price: "3,299",
      cross: "5,499",
      stars: 4.5,
      review: "3,679",
      type: "sneakers",
      bestof: "shoesallbest",
      off: "40",
    },

    // Sports
    {
      id: "61",
      companyname: "REEBOK ",
      name: "Force runner M Running Shoes For Men  (White)",
      image:
        "https://i.postimg.cc/4dsxBZVY/Force-runner-M-Running-Shoes-For-Men-White.webp",
      price: "2,239",
      cross: "4,999",
      stars: 4,
      off: "53",
      review: "2,229",
      type: "Sports",
      diss: "",
    },
    {
      id: "62",
      companyname: "Abros",
      name: "Running Shoes For Men  (Navy)",
      image: "https://i.postimg.cc/0NZ1ZZrG/Running-Shoes-For-Men-Navy.webp",
      price: "1,599",
      cross: "1,799",
      off: "11",
      stars: 4,
      review: "215",
      type: "Sports",
      diss: "",
    },
    {
      id: "63",
      companyname: "ADIDAS ",
      name: "RayRun M Running Shoes For Men  (Grey)",
      image:
        "https://i.postimg.cc/BQnVTDKD/Ray-Run-M-Running-Shoes-For-Men-Grey.webp",
      price: "2,299",
      cross: "4,599",
      off: "50",
      stars: 4.2,
      review: "1,866",
      type: "Sports",
      diss: "",
    },
    {
      id: "64",
      companyname: "Fila",
      name: " Fila Men Blue TAKIYO Running Shoes Running Shoes For Men  (Blue)",
      image:
        "https://i.postimg.cc/Y9dJ79wJ/Fila-Men-Blue-TAKIYO-Running-Shoes-Running-Shoes-For-Men-Blue.webp",
      price: "2,699",
      cross: "2,999",
      off: "8",
      stars: 4.2,
      review: "89",
      type: "Sports",
      diss: "",
    },
    {
      id: "65",
      companyname: "REEBOK",
      name: "Fair weather 2.0 M Running Shoes For Men  (Blue)",
      image:
        "https://i.postimg.cc/6p9n2L4J/Fair-weather-2-0-M-Running-Shoes-For-Men-Blue-j.webp",
      price: "2,199",
      cross: "4,999",
      off: "53",
      stars: 4,
      review: "192",
      type: "Sports",
      diss: "",
    },
    {
      id: "66",
      companyname: "PUMA",
      name: "Cell Vive Intake Running Shoes For Men  (Grey)",
      image:
        "https://i.postimg.cc/XqY6BPWB/Cell-Vive-Intake-Running-Shoes-For-Men-Grey.webp",
      price: "3,399",
      cross: "6,999",
      off: "52",
      stars: 4.4,
      review: "289",
      type: "Sports",
      diss: "",
    },

    // High Ankle
    {
      id: "67",
      companyname: "RED TAPE ",
      name: "Sneaker Casual Shoes for Men | Soft Cushioned Insole, Slip-Resistance High Tops For Men  (White)",
      image:
        "https://i.postimg.cc/9FMKZSRC/Sneaker-Casual-Shoes-for-Men-Slip-Resistance-High-Tops-For-Men.webp",
      price: "1,679",
      cross: "5,499",
      stars: 4.3,
      off: "70",
      review: "8,429",
      type: "High-Ankle",
      diss: "",
    },
    {
      id: "68",
      companyname: "PUMA ",
      name: "Rebound Layup Wide High Tops For Men ",
      image:
        "https://i.postimg.cc/8C9XdPvS/Rebound-Layup-Wide-High-Tops-For-Men-webp.webp",
      price: "3,339",
      cross: "6,999",
      stars: 4.4,
      off: "52",
      review: "5,229",
      type: "High-Ankle",
      diss: "",
    },
    {
      id: "69",
      companyname: "asian",
      name: "Sneaker Casual Shoes for Men | Soft Cushioned Insole, Slip-Resistance High Tops For Men  (Blue, White)",
      image: "https://i.postimg.cc/13GJVh0W/Sneaker-Casual-Shoes-for-Men.webp",
      price: "1,139",
      cross: "1,999",
      stars: 4,
      off: "43",
      review: "1,229",
      type: "High-Ankle",
      diss: "",
    },
    {
      id: "70",
      companyname: "PUMA",
      name: "Peak High Tops For Men  (Blue)",
      image: "https://i.postimg.cc/KcKGVtn7/Peak-High-Tops-For-Men.webp",
      price: "2,199",
      cross: "5,499",
      stars: 4.1,
      off: "53",
      review: "609",
      type: "High-Ankle",
      diss: "",
    },
    {
      id: "71",
      companyname: "HRX by Hrithik Roshan ",
      name: "CLUB CULTURE High Tops For Men  (White)",
      image:
        "https://i.postimg.cc/y8bG5p0s/CLUB-CULTURE-High-Tops-For-Men-White.webp",
      price: "3,557",
      cross: "4,999",
      stars: 4,
      off: "20",
      review: "379",
      type: "High-Ankle",
      diss: "",
    },
    {
      id: "72",
      companyname: "PUMA ",
      name: "Backcourt Mid x 1DER Casuals For Men  (White)",
      image:
        "https://i.postimg.cc/XvcV9yrR/Backcourt-Mid-x-1-DER-Casuals-For-Men-White.webp",
      price: "4,459",
      cross: "7,999",
      stars: 4,
      off: "44",
      review: "629",
      type: "High-Ankle",
      diss: "",
    },

    // watch
    // 20-80%off

    {
      id: "73",
      companyname: "Fastrack ",
      name: "Minimalists Analog Watch - For Men 38024PP25",
      image: "https://i.postimg.cc/zBkd4f70/Fastrack-minimalist-analog.webp",
      price: "850",
      cross: "999",
      stars: 4.3,
      review: "2,33,679",
      type: "watch",
      bestof: "watchallbest",
    },
    {
      id: "74",
      companyname: "Fastrack ",
      name: "Analog Watch - For Men NP1771SM03",
      image: "https://i.postimg.cc/7ZfLKsDW/Titan-analog-watch.webp",
      price: "1,939",
      cross: "3,499",
      stars: 4.4,
      review: "34,679",
      type: "watch",
      bestof: "watchallbest",
    },
    {
      id: "75",
      companyname: "TOMMY HILFIGER ",
      name: "Analog Watch - For Men TH1792059",
      image: "https://i.postimg.cc/W32KNy9N/TOMMY-HILFIGER-webp.webp",
      price: "12,459",
      cross: "15,899",
      stars: 4.3,
      review: "579",
      type: "watch",
      bestof: "watchallbest",
    },
    {
      id: "76",
      companyname: "SONATA ",
      name: "Sonata Essential Analog Watch - For Men NP77083SM01",
      image:
        "https://i.postimg.cc/XNTDzXwc/Sonata-Essential-Analog-Watch-For-Men-NP77083-SM01.webp",
      price: "1,299",
      cross: "1,499",
      stars: 4.3,
      review: "17,379",
      type: "watch",
      bestof: "watchallbest",
    },
    {
      id: "77",
      companyname: "Fastrack ",
      name: "Bronson Analog Watch - For Men ME3218",
      image:
        "https://i.postimg.cc/CK3m6Q8M/Bronson-Analog-Watch-For-Men-ME3218.webp",
      price: "21,299",
      cross: "22,499",
      stars: 4.1,
      review: "79",
      type: "watch",
      bestof: "watchallbest",
    },
    {
      id: "78",
      companyname: "A/X ARMANI EXCHANGE ",
      name: "Cayde Analog Watch - For Men AX2701",
      image:
        "https://i.postimg.cc/YCs464GY/Cayde-Analog-Watch-For-Men-AX2701.webp",
      price: "13,299",
      cross: "14,499",
      stars: 4.1,
      review: "82",
      type: "watch",
      bestof: "watchallbest",
    },

    // Appliances

    // television
    {
      id: "79",
      name: "Acer Advanced I Series 108 cm (43 inch) Full HD LED Smart Google TV 2023 Edition  (AR43GR2841FDFL)",
      image:
        "https://i.postimg.cc/Bb8fBH10/Acer-Advanced-I-Series-108-cm-43-inch-Full-HD-LED-Smart-Google-TV-2023-Editionwebp.webp",
      price: "19,999",
      cross: "31,699",
      stars: 4.1,
      review: "892",
      type: "television",
    },
    {
      id: "80",
      name: "Mi 5A 108 cm (43 inch) Full HD LED Smart Android TV with Dolby Audio (2022 Model)",
      image: {
        img1: "https://rukminim2.flixcart.com/image/416/416/xif0q/television/a/p/z/-original-imagt86krs3tu9zh.jpeg?q=70",

        img2: "https://rukminim2.flixcart.com/image/416/416/l2f20sw0/television/y/f/r/l43m7-eain-mi-original-imagdrtn9rp8vkgj.jpeg?q=70",
        img3: "https://rukminim2.flixcart.com/image/416/416/l2f20sw0/television/x/h/k/l43m7-eain-mi-original-imagdrtnwqeunchj.jpeg?q=70",
        img4: "https://rukminim2.flixcart.com/image/416/416/l2f20sw0/television/g/x/e/l43m7-eain-mi-original-imagdrtnfmrjrcrt.jpeg?q=70",
        img5: "https://rukminim2.flixcart.com/image/416/416/l2f20sw0/television/5/z/g/l43m7-eain-mi-original-imagdrtnxt8g8n5r.jpeg?q=70",
      },

      price: "22,999",
      cross: "35,999",
      stars: 4.7,
      review: "3,73,753",
      type: "television",
      bestof: "itallbest",
    },
    {
      id: "81",
      name: "Vu Premium TV 108 cm (43 inch) Full HD LED Smart Android TV 2022 Edition  (43GA-Android)",
      image:
        "https://i.postimg.cc/wMSMX6Mw/Vu-Premium-TV-108-cm-43-inch-Full-HD-LED-Smart-Android-TV-2022-Edition-43-GA-Android-webp.webp",
      price: "20,999",
      cross: "35,999",
      stars: 4.2,
      review: "1,253",
      type: "television",
    },
    {
      id: "82",
      name: "SAMSUNG Crystal Vision 4K iSmart with Voice Assistant 108 cm (43 inch) Ultra HD (4K) LED Smart Tizen TV 2023 Edition with Video Calling & IOT Sensors for Light & Camera  (UA43CUE70AKLXL)",
      image: {
        img1: "https://rukminim2.flixcart.com/image/416/416/xif0q/television/j/2/j/-original-imagtq4hqqt37tgx.jpeg?q=70",

        img2: "https://rukminim2.flixcart.com/image/416/416/xif0q/television/k/h/g/-original-imags2ygswqxzuhu.jpeg?q=70",
        img3: "https://rukminim2.flixcart.com/image/416/416/xif0q/television/o/d/v/-original-imagu2h6fzgheg4a.jpeg?q=70",
        img4: "https://rukminim2.flixcart.com/image/416/416/xif0q/television/c/x/q/ua43cue70aklxl-samsung-original-imagrudzfmqsffca.jpeg?q=70",
        img5: "https://rukminim2.flixcart.com/image/416/416/xif0q/television/x/w/n/ua43cue70aklxl-samsung-original-imagrudz6rvqezke.jpeg?q=70",
      },

      price: "32,999",
      cross: "52,999",
      stars: 4.4,
      review: "39,353",
      type: "television",
      bestof: "itallbest",
    },
    {
      id: "83",
      name: "ONIDA 108 cm (43 inch) Ultra HD (4K) LED Smart Google TV 2023 Edition with Dolby Atmos Vision & HDR10  (43UIG)",
      image:
        "https://i.postimg.cc/9MBF4dHF/ONIDA-108-cm-43-inch-Ultra-HD-4-K-LED-Smart-Google-TV-2023-Edition-with-Dolby-Atmos-Vision-HDR1.webp",
      price: "22,999",
      cross: "35,999",
      stars: 4,
      review: "3,453",
      type: "television",
    },
    {
      id: "84",
      name: "SONY Bravia 108 cm (43 inch) Ultra HD (4K) LED Smart Google TV 2022 Edition  (KD - 43X74K)",
      image: {
        img1: "https://rukminim2.flixcart.com/image/416/416/xif0q/television/6/g/p/-original-imagvgcjagmhmxfz.jpeg?q=70",

        img2: "https://rukminim2.flixcart.com/image/416/416/l3929ow0/television/o/s/b/kd-43x75k-in5-sony-original-imagef42anpamkbv.jpeg?q=70",
        img3: "https://rukminim2.flixcart.com/image/416/416/l3929ow0/television/o/s/b/kd-43x75k-in5-sony-original-imagef42anpamkbv.jpeg?q=70",
        img4: "https://rukminim2.flixcart.com/image/416/416/l3bx5e80/television/g/g/h/-original-imageh37qwmnbzh4.jpeg?q=70",
        img5: "https://rukminim2.flixcart.com/image/416/416/l3929ow0/television/f/2/f/kd-32w830k-in5-sony-original-imagef45dghjhqyg.jpeg?q=70",
      },
      price: "34,499",
      cross: "59,699",
      stars: 4.6,
      review: "47,953",
      type: "television",
      bestof: "itallbest",
    },

    // Up to 70% Off
    {
      id: "85",
      companyname: "A/X ARMANI EXCHANGE ",
      name: "Singer FM 3223 - R Electric Sewing Machine  ( Built-in Stitches 23)",
      image: "https://i.postimg.cc/rytxj257/tailor-machine.webp",
      price: "15,299",
      cross: "17,499",
      stars: 4.3,
      review: "282",
      type: "70%-Off",
    },
    {
      id: "86",
      companyname: "A/X ARMANI EXCHANGE ",
      name: "Singer FM 3223 - R Electric Sewing Machine  ( Built-in Stitches 23)",
      image:
        "https://i.postimg.cc/tJzcwZL4/BUI-Portable-Bori-Closer-Machine-Single-Needle-D-Model-Without-Oil-Pump-Electric-Sewing-Machine.webp",
      price: "5,299",
      cross: "6,499",
      stars: 4.1,
      review: "42",
      type: "70%-Off",
    },
    {
      id: "87",
      companyname: "A/X ARMANI EXCHANGE ",
      name: "Livguard LG900_IT 1560STJ Tubular Inverter Battery  ((150 Ah+ 800VA))",
      image:
        "https://i.postimg.cc/PxC3KVMK/Livguard-LG900-IT-1560-STJ-Tubular-Inverter-Battery-150-Ah-800-VA.webp",
      price: "18,599",
      cross: "22,999",
      stars: 4.2,
      review: "32",
      type: "70%-Off",
    },
    {
      id: "88",
      companyname: "A/X ARMANI EXCHANGE ",
      name: "BAJAJ MX 3 Neo 1250 W Steam Iron  (Blue, White)",
      image:
        "https://i.postimg.cc/fTycdSBj/BAJAJ-MX-3-Neo-1250-W-Steam-Iron-Blue-White.webp",
      price: "1,099",
      cross: "1,499",
      stars: 4.1,
      review: "6,282",
      type: "70%-Off",
    },
    {
      id: "89",
      companyname: "A/X ARMANI EXCHANGE ",
      name: "EUREKA FORBES Fast Clean Bagless Dry Vacuum Cleaner with Reusable Dust Bag  (Red and Black)",
      image:
        "https://i.postimg.cc/cH87vvZ4/EUREKA-FORBES-Fast-Clean-Bagless-Dry-Vacuum-Cleaner-with-Reusable-Dust-Bag-Red-and-Black.webp",
      price: "3,299",
      cross: "7,499",
      stars: 4,
      review: "5,582",
      type: "70%-Off",
      bestof: "Appliancesallbest",
    },
    {
      id: "90",
      companyname: "A/X ARMANI EXCHANGE ",
      name: "Mi Robot Vacuum-Mop P (STYTJ02YM) Robotic Floor Cleaner with 2 in 1 Mopping and Vacuum (WiFi Connectivity, Google Assistant and Alexa)  (Black)",
      image:
        "https://i.postimg.cc/Kvn1RnMH/Mi-Robot-Vacuum-Mop-P-STYTJ02-YM-Robotic-Floor-Cleaner-with-2-in-1-Mopping-and-Vacuum-Wi-Fi-Connect.webp",
      price: "23,299",
      cross: "26,499",
      stars: 4.2,
      review: "3,582",
      type: "70%-Off",
    },

    // Up to 75% Off
    {
      id: "91",
      companyname: "A/X ARMANI EXCHANGE ",
      name: "Pigeon 40-Litre 15593 Oven Toaster Grill (OTG)  (Black)",
      image:
        "https://i.postimg.cc/7LpVq37Z/Pigeon-40-Litre-15593-Oven-Toaster-Grill-OTG-Black.webp",
      price: "7,299",
      cross: "12,499",
      stars: 4,
      review: "582",
      type: "75%-Off",
      bestof: "Appliancesallbest",
    },
    {
      id: "92",
      companyname: "A/X ARMANI EXCHANGE ",
      name: "Mr. Butler RoboChef 9-in-1 Multi-Use Automatic, 6 Litre capacity Electric Pressure Cooker  (6 L, Black, Silver)",
      image:
        "https://i.postimg.cc/RZ197dSj/Mr-Butler-Robo-Chef-9-in-1-Multi-Use-Automatic-6-Litre-capacity-Electric-Pressure-Cooker-6-L-Bla.webp",
      price: "7,299",
      cross: "13,499",
      stars: 4.4,
      review: "82",
      type: "75%-Off",
    },
    {
      id: "93",
      companyname: "A/X ARMANI EXCHANGE ",
      name: "iBELL SM1515 Sandwich Maker with Floating Hinges, 1000 Watt, Panini / Grill / Toast, Grill  (Black, Silver)",
      image:
        "https://i.postimg.cc/HLcLQ5N5/i-BELL-SM1515-Sandwich-Maker-with.webp",
      price: "1,699",
      cross: "4,499",
      stars: 4.2,
      review: "682",
      type: "75%-Off",
    },
    {
      id: "94",
      companyname: "A/X ARMANI EXCHANGE ",
      name: "ULTRA Perfect + 2.0 L Wet Grinder  (Purple, White)",
      image:
        "https://i.postimg.cc/wByh71c4/ULTRA-Perfect-2-0-L-Wet-Grinder-Purple-White.webp",
      price: "10,499",
      cross: "11,999",
      stars: 4.3,
      review: "1,982",
      type: "75%-Off",
    },
    {
      id: "95",
      companyname: "A/X ARMANI EXCHANGE ",
      name: "BAJAJ Gx8 GX8 750 W Mixer Grinder (3 Jars, White)",
      image:
        "https://i.postimg.cc/9QzxYFYZ/BAJAJ-Gx8-GX8-750-W-Mixer-Grinder-3-Jars-White.webp",
      price: "5,699",
      cross: "8,499",
      stars: 4.3,
      review: "23,582",
      type: "75%-Off",
    },
    {
      id: "96",
      companyname: "A/X ARMANI EXCHANGE ",
      name: "HAVELLS Insta cook ET-X Induction Cooktop  (Black, Push Button)",
      image:
        "https://i.postimg.cc/6q2LXQ6n/HAVELLS-Insta-cook-ET-X-Induction-Cooktop-Black-Push-Button.webp",
      price: "3,279",
      cross: "5,009",
      stars: 4.3,
      review: "4,182",
      type: "75%-Off",
      bestof: "Appliancesallbest",
    },

    // Washing Machines
    {
      id: "97",
      companyname: "A/X ARMANI EXCHANGE ",
      name: "IFB 8 kg Powered by AI, 5 Star, 4 years Comprehensive Warranty with 2x Steam Cycle Fully Automatic Front Load Washing Machine with In-built Heater White  (Senator Neo VXS 8012)",
      image:
        "https://i.postimg.cc/d144v1MV/IFB-8-kg-Powered-by-AI-5-Star-4-years-Comprehensive-Warranty-with-2x-Steam-Cycle-Fully-Automatic-F.webp",
      price: "32,999",
      cross: "43,999",
      stars: 4.3,
      review: "81,582",
      type: "Washing-Machines",
      bestof: "WashingMachinesallbest",
    },
    {
      id: "98",
      companyname: "A/X ARMANI EXCHANGE ",
      name: "SAMSUNG 8 kg 5 Star, AI Ecobubble,Wi-Fi Enabled ,Hygiene Steam,Digital Inverter Fully Automatic Front Load Washing Machine with In-built Heater Black  (WW80T504DAB1TL)",
      image:
        "https://i.postimg.cc/cLtXfXQ0/SAMSUNG-8-kg-5-Star-AI-Ecobubble-Wi-Fi-Enabled-Hygiene-Steam-Digital-Inverter-Fully-Automatic.webp",
      price: "36,999",
      cross: "44,459",
      stars: 4.4,
      review: "14,762",
      type: "Washing-Machines",
      bestof: "Appliancesallbest",
    },
    {
      id: "99",
      companyname: "A/X ARMANI EXCHANGE ",
      name: "LG 8.5 kg 5 Star with Roller Jet Pulsator with Soak, Wind Jet Dry and Rat Away, 6 Kg (Spin Tub Capacity) Semi Automatic Top Load Washing Machine Maroon  (P8530SRAZ)",
      image:
        "https://i.postimg.cc/qR6355vv/LG-8-5-kg-5-Star-with-Roller-Jet-Pulsator-with-Soak-Wind-Jet-Dry-and-Rat-Away-6-Kg-Spin-Tub-Capac.webp",
      price: "19,599",
      cross: "23,999",
      stars: 4,
      review: "3,542",
      type: "Washing-Machines",
      bestof: "WashingMachinesallbest",
    },
    {
      id: "100",
      companyname: "A/X ARMANI EXCHANGE ",
      name: "Whirlpool 6.5 kg Magic Clean 5 Star Fully Automatic Top Load Washing Machine Grey  (MAGIC CLEAN 6.5 GENX GREY 5Yr MW)",
      image:
        "https://i.postimg.cc/CLsm7z26/Whirlpool-6-5-kg-Magic-Clean-5-Star-Fully-Automatic-Top-Load-Washing-Machine-Grey-MAGIC-CLEAN-6-5.webp",
      price: "14,470",
      cross: "18,299",
      stars: 4.2,
      review: "24,654",
      type: "Washing-Machines",
      bestof: "WashingMachinesallbest",
    },
    {
      id: "101",
      companyname: "A/X ARMANI EXCHANGE ",
      name: "Whirlpool 8 kg Fully Automatic Front Load Washing Machine with In-built Heater Black  (XO8014BYS)",
      image:
        "https://i.postimg.cc/DfjqwLth/Whirlpool-8-kg-Fully-Automatic-Front-Load-Washing-Machine-with-In-built-Heater-Black-XO8014-BYS.webp",
      price: "36,499",
      cross: "50,399",
      stars: 4,
      review: "1,682",
      type: "Washing-Machines",
      bestof: "Appliancesallbest",
    },
    {
      id: "102",
      companyname: "A/X ARMANI EXCHANGE ",
      name: "IFB 7 kg Powered by AI, 5 Star, 4 years Comprehensive Warranty with 2x Steam Cycle Fully Automatic Front Load Washing Machine with In-built Heater Brown  (DIVA AQUA MXS 7010)",
      image:
        "https://i.postimg.cc/ncW68dZQ/IFB-7-kg-Powered-by-AI-5-Star-4-years-Comprehensive-Warranty-with-2x-Steam-Cycle-Fully-Automatic-F.webp",
      price: "28,900",
      cross: "37,470",
      stars: 4.3,
      review: "84,542",
      type: "Washing-Machines",
      bestof: "Appliancesallbest",
    },

    // Refrigerators

    {
      id: "103",
      companyname: "A/X ARMANI EXCHANGE ",
      name: "realme TechLife 280 L Frost Free Double Door 3 Star Refrigerator  (Black Uniglass, 281JF3RMBG)",
      image:
        "https://i.postimg.cc/gjqxZwDv/realme-Tech-Life-280-L-Frost-Free-Double-Door-3-Star-Refrigerator-Black-Uniglass-281-JF3-RMBG.webp",
      price: "24,999",
      cross: "32,499",
      stars: 4.3,
      review: "982",
      type: "Refrigerators",
    },
    {
      id: "104",
      companyname: "A/X ARMANI EXCHANGE ",
      name: "Lloyd 587 L Frost Free Side by Side Refrigerator  (Glass Gold, GLSF590DGGT1GB)",
      image:
        "https://i.postimg.cc/HLRzSKC6/Lloyd-587-L-Frost-Free-Side-by-Side-Refrigerator-Glass-Gold-GLSF590-DGGT1-GB.webp",
      price: "68,699",
      cross: "80,499",
      stars: 4.4,
      review: "62",
      type: "Refrigerators",
    },
    {
      id: "105",
      companyname: "A/X ARMANI EXCHANGE ",
      name: "Whirlpool 570 L Frost Free Side by Side Inverter Technology Star Refrigerator  (Silver, WS SBS 570 STEEL (SH))",
      image:
        "https://i.postimg.cc/28n53B6y/Whirlpool-570-L-Frost-Free-Side-by-Side-Inverter-Technology-Star-Refrigerator-Silver-WS-SBS-570-S.webp",
      price: "71,999",
      cross: "89,499",
      stars: 4.3,
      review: "1,282",
      type: "Refrigerators",
    },
    {
      id: "106",
      companyname: "A/X ARMANI EXCHANGE ",
      name: "Liebherr 420 L Frost Free Double Door 2 Star Refrigerator  (Cobalt Steel, TDcsB 4740 - 21)",
      image:
        "https://i.postimg.cc/wBwctj2y/Liebherr-420-L-Frost-Free-Double-Door-2-Star-Refrigerator-Cobalt-Steel-TDcs-B-4740-21.webp",
      price: "51,299",
      cross: "71,499",
      stars: 4,
      review: "582",
      type: "Refrigerators",
      bestof: "Refrigeratorsallbest",
    },
    {
      id: "107",
      companyname: "A/X ARMANI EXCHANGE ",
      name: "LG 687 L Frost Free Side by Side Refrigerator with with Smart ThinQ(WiFi Enabled)  (Shiny Steel/Platinum Silver3, GC-B247SLUV)",
      image:
        "https://i.postimg.cc/KY2s7jt0/LG-687-L-Frost-Free-Side-by-Side-Refrigerator-with-with-Smart.webp",
      price: "79,999",
      cross: "1,04,499",
      stars: 4.6,
      review: "943",
      type: "Refrigerators",
    },
    {
      id: "108",
      companyname: "A/X ARMANI EXCHANGE ",
      name: "Godrej 670 L Frost Free French Door Bottom Mount Refrigerator  (Grey Black, RM EONVELVET 685 RIT GR BK)",
      image:
        "https://i.postimg.cc/Pq1b4MdD/Godrej-670-L-Frost-Free-French-Door-Bottom-Mount-Refrigerator-Grey-Black-RM-EONVELVET-685-RIT-GR.webp",
      price: "86,499",
      cross: "1,08,499",
      stars: 4.1,
      review: "290",
      type: "Refrigerators",
    },

    // cloths

    // men's t-shirt

    {
      id: "109",
      companyname: "Waji Va ",
      name: "Men Regular Fit Self Design Casual Shirt",
      image: "https://i.postimg.cc/C11SpCR7/Waji-Va.webp",
      price: "249",
      cross: "699",
      stars: 4.1,
      off: 64,
      type: "mens-t-shirt",
    },
    {
      id: "110",
      companyname: "3BROS ",
      name: "Men Self Design Polo Neck Cotton Blend (220 gsm) Green T-Shirt",
      image:
        "https://i.postimg.cc/cCTdpDmF/Men-Self-Design-Polo-Neck-Cotton-Blend-220-gsm-Green-T-Shirt.webp",
      price: "299",
      cross: "799",
      stars: 4.1,
      off: 70,
      review: "310",
      type: "mens-t-shirt",
    },
    {
      id: "111",
      companyname: "HIGHLANDER",
      name: "Men Slim Fit Solid Cut Away Collar Casual Shirt",
      image:
        "https://i.postimg.cc/vT7CkcQM/Men-Slim-Fit-Solid-Cut-Away-Collar-Casual-Shirt.webp",
      price: "526",
      cross: "1,899",
      stars: 3.8,
      off: 72,
      review: "570",
      type: "mens-t-shirt",
    },
    {
      id: "112",
      companyname: "U.S. POLO ASSN.",
      name: "Men Slim Fit Checkered Spread Collar Casual Shirt",
      image:
        "https://i.postimg.cc/RhR4fPJc/Men-Slim-Fit-Checkered-Spread-Collar-Casual-Shirt.webp",
      price: "1,499",
      cross: "2,499",
      stars: 4.2,
      off: 44,
      review: "120",
      type: "mens-t-shirt",
    },
    {
      id: "113",
      companyname: "Allen Solly ",
      name: "Men Solid Polo Neck Pure Cotton White T-Shirt",
      image:
        "https://i.postimg.cc/C186WzF5/Men-Solid-Polo-Neck-Pure-Cotton-White-T-Shirt.webp",
      price: "699",
      cross: "999",
      stars: 3.5,
      off: 35,
      review: "50",
      type: "mens-t-shirt",
    },
    {
      id: "114",
      companyname: "Classic Polo ",
      name: "Men Solid Polo Neck Cotton Blend Gold T-Shirt",
      image:
        "https://i.postimg.cc/vmCGrgqZ/Men-Solid-Polo-Neck-Cotton-Blend-Gold-T-Shirt.webp",
      price: "599",
      cross: "899",
      stars: 3.8,
      off: 36,
      review: "57",
      type: "mens-t-shirt",
    },

    // men's shirt

    {
      id: "115",
      companyname: "THE BEAR HOUSE ",
      name: "Men Slim Fit Solid Button Down Collar Casual Shirt",
      image:
        "https://i.postimg.cc/kgJbw0hL/Men-Slim-Fit-Solid-Button-Down-Collar-Casual-Shirt.webp",
      price: "873",
      cross: "2,499",
      stars: 4.2,
      off: 65,
      type: "mens-shirt",
      review: "835",
    },
    {
      id: "116",
      companyname: "Dennis Lingo ",
      name: "Men Slim Fit Striped Slim Collar Casual Shirt ",
      image:
        "https://i.postimg.cc/Pf957BVP/Men-Slim-Fit-Striped-Slim-Collar-Casual-Shirt.webp",
      price: "499",
      cross: "2,499",
      stars: 4.2,
      off: 80,
      review: "6,439",
      type: "mens-shirt",
    },
    {
      id: "117",
      companyname: "Majestic Man ",
      name: "Men Slim Fit Checkered Spread Collar Casual Shirt",
      image:
        "https://i.postimg.cc/L4Db61ZP/Men-Slim-Fit-Checkered-Spread-Collar-Casual-Shirtt.webp",
      price: "459",
      cross: "1,499",
      stars: 4.2,
      off: 69,
      review: "1,430",
      type: "mens-shirt",
    },
    {
      id: "118",
      companyname: "Snitch ",
      name: "Men NA Fit Printed Lapel Collar Casual Shirt",
      image:
        "https://i.postimg.cc/mr0KGfJg/Men-NA-Fit-Printed-Lapel-Collar-Casual-Shirt.webp",
      price: "1,499",
      cross: "2,499",
      stars: 4.2,
      off: 44,
      review: "120",
      type: "mens-shirt",
    },
    {
      id: "119",
      companyname: "U.S. Polo Assn. Denim Co. ",
      name: "Men Slim Fit Solid Cut Away Collar Casual Shirt",
      image:
        "https://i.postimg.cc/kgjvSQyr/Men-Slim-Fit-Solid-Cut-Away-Collar-Casual-Shirt.webp",
      price: "1,266",
      cross: "2.199",
      stars: 4.2,
      off: 43,
      review: "199",
      type: "mens-shirt",
    },
    {
      id: "120",
      companyname: "Roadster ",
      name: "Men Regular Fit Checkered Spread Collar Casual Shirt",
      image:
        "https://i.postimg.cc/zXL1SmZ8/Men-Regular-Fit-Checkered-Spread-Collar-Casual-Shirt.webp",
      price: "615",
      cross: "1,499",
      stars: 4.2,
      off: 58,
      review: "2,237",
      type: "mens-shirt",
    },

    // women cloths

    {
      id: "121",
      companyname: "LIBAS ",
      name: "Women Solid Cotton Blend Straight Kurta  (Maroon)",
      image:
        "https://i.postimg.cc/vTQJCBm6/Women-Solid-Cotton-Blend-Straight-Kurta-Maroon.webp",
      price: "389",
      cross: "1,299",
      stars: 4.1,
      off: 70,
      type: "women",
      review: "22,587",
    },
    {
      id: "122",
      companyname: "Ewedoos",
      name: "Women Viscose Rayon Kurta Pant Dupatta Set",
      image:
        "https://i.postimg.cc/gkZZ6Yp3/Women-Viscose-Rayon-Kurta-Pant-Dupatta-Set.webp",
      price: "559",
      cross: "2,499",
      stars: 3.9,
      off: 77,
      review: "12,339",
      type: "women",
    },
    {
      id: "123",
      companyname: "LIBAS",
      name: "Women Cotton Blend Kurta Palazzo Set",
      image:
        "https://i.postimg.cc/W1zndd8S/Women-Cotton-Blend-Kurta-Palazzo-Set.webp",
      price: "1,179",
      cross: "2,799",
      stars: 4.2,
      off: 58,
      review: "1,930",
      type: "women",
    },
    {
      id: "124",
      companyname: "Snitch ",
      name: "Women Viscose Rayon Kurta Trouser Dupatta Set",
      image:
        "https://i.postimg.cc/8CYJZb2f/Women-Viscose-Rayon-Kurta-Trouser-Dupatta-Set.webp",
      price: "1,799",
      cross: "6,999",
      stars: 3.5,
      off: 75,
      review: "80",
      type: "women",
    },
    {
      id: "125",
      companyname: "Indo Era ",
      name: "Women Chiffon Kurta Trouser Set",
      image:
        "https://i.postimg.cc/gkjsJMG1/Women-Chiffon-Kurta-Trouser-Set.webp",
      price: "1,299",
      cross: "6.199",
      stars: 3.9,
      off: 79,
      review: "356",
      type: "women",
    },
    {
      id: "126",
      companyname: "Safaa ",
      name: "Unstitched Acrylic Blend Kurta & Palazzo Material Self Design",
      image:
        "https://i.postimg.cc/BZD69FLD/Unstitched-Acrylic-Blend-Kurta-Palazzo-Material-Self-Design.webp",
      price: "1,649",
      cross: "3,999",
      stars: 4,
      off: 58,
      review: "1,543",
      type: "women",
    },

    // toy
    {
      id: "127",
      companyname: "",
      name: "Little's Junior Stacking Ring Toys for Kids,  (Multicolor)",
      image:
        "https://i.postimg.cc/KvXWvxtk/Little-s-Junior-Stacking-Ring-Toys-for-Kids-Multicolor.webp",
      price: "228",
      cross: "249",
      stars: 4.3,
      off: 8,
      review: "41,543",
      type: "toy",
    },
    {
      id: "127",
      companyname: "",
      name: "TAPUJI Dancing Cactus Repeats What You Say,Electronic Plush Toy with Lighting,Singing Cactus Recording and Repeat Your Words for Education Toys  (Green)",
      image:
        "https://i.postimg.cc/7Z11MyCR/TAPUJI-Dancing-Cactus-Repeats-What-You-Say-Electronic-Plush-Toy-with-Lighting-Singing-Cactus-Recordi.webp",
      price: "349",
      cross: "1,899",
      stars: 3.9,
      off: 80,
      review: "10,943",
      type: "toy",
    },
    {
      id: "128",
      companyname: "",
      name: "SALEOFF Xylophone 2-in-1 Premium Piano 5 Key Scale Musical Toy For Kids - 141  (Multicolor)",
      image:
        "https://i.postimg.cc/zBvPcfKv/SALEOFF-Xylophone-2-in-1-Premium-Piano-5-Key-Scale-Musical-Toy-For-Kids-141-Multicolor.webp",
      price: "449",
      cross: "799",
      stars: 3.4,
      off: 37,
      review: "245",
      type: "toy",
    },
    {
      id: "129",
      companyname: "",
      name: "Myhoodwink Rideons & Wagons Non Battery Operated Ride On  (Multicolor)",
      image:
        "https://i.postimg.cc/0NsTcm8C/Myhoodwink-Rideons-Wagons-Non-Battery-Operated-Ride-On-Multicolor.webp",
      price: "999",
      cross: "1,999",
      stars: 4.2,
      off: 50,
      review: "1,493",
      type: "toy",
    },
    {
      id: "130",
      companyname: "",
      name: "M Fire Soft Bullet Toy Gun7643 Guns & Darts  (Multicolor)",
      image:
        "https://i.postimg.cc/fLn2ChDS/M-Fire-Soft-Bullet-Toy-Gun7643-Guns-Darts-Multicolor.webp",
      price: "229",
      cross: "999",
      stars: 4.2,
      off: 77,
      review: "22,743",
      type: "toy",
    },
    {
      id: "131",
      companyname: "Safaa ",
      name: "toyden Roundle 32  (Multicolor)",
      image: "https://i.postimg.cc/B6Rmb9wn/toyden-Roundle-32-Multicolor.webp",
      price: "949",
      cross: "1,999",
      stars: 4,
      off: 52,
      review: "243",
      type: "toy",
    },

    // beauty

    {
      id: "132",
      companyname: "",
      name: "HIMALAYA Baby Lotion  (100 ml)",
      image:
        "https://i.postimg.cc/MKdXkyPd/HIMALAYA-Baby-Lotion-100-ml-webp.webp",
      price: "100",
      cross: "110",
      stars: 4.2,
      off: 10,
      review: "7,987",
      type: "Beauty",
    },
    {
      id: "133",
      companyname: "",
      name: "Little's Organix Baby Shampoo  (400 ml)",
      image:
        "https://i.postimg.cc/VLrMFZLX/Little-s-Organix-Baby-Shampoo-400-ml.webp",
      price: "236",
      cross: "320",
      stars: 4.3,
      off: 26,
      review: "1,243",
      type: "Beauty",
    },
    {
      id: "133",
      companyname: "",
      name: "JOHNSON'S BABY No More Tears Shampoo (500ml+200ml) Home & Travel Combo Pack  (Yellow)",
      image:
        "https://i.postimg.cc/zv7Fs0cq/JOHNSON-S-BABY-No-More-Tears-Shampoo-500ml-200ml-Home-Travel-Combo-Pack-Yellow.webp",
      price: "522",
      cross: "695",
      stars: 4.3,
      off: 26,
      review: "285",
      type: "Beauty",
    },
    {
      id: "134",
      companyname: "",
      name: "JOHNSON'S BABY Lotion (500ml+200ml) Home & Travel Combo pack  (White)",
      image:
        "https://i.postimg.cc/jqf5MDJk/JOHNSON-S-BABY-Lotion-500ml-200ml-Home-Travel-Combo-pack-White.webp",
      price: "439",
      cross: "645",
      stars: 4,
      off: 31,
      review: "226",
      type: "Beauty",
    },
    {
      id: "135",
      companyname: "",
      name: "baby Dove Rich Moisture Shampoo  (200 ml)",
      image:
        "https://i.postimg.cc/W4KZJxQD/baby-Dove-Rich-Moisture-Shampoo-200-ml.webp",
      price: "212",
      cross: "220",
      stars: 4,
      off: 3,
      review: "7,043",
      type: "Beauty",
    },

    {
      id: "136",
      companyname: "",
      name: "Dettol Germ Protection ph-Balanced Liquid Refill, Skincare Hand Wash Pouch  (675 ml)",
      image:
        "https://i.postimg.cc/wvQ6dmc6/Dettol-Germ-Protection-ph-Balanced-Liquid-Refill-Skincare-Hand-Wash-Pouch-675-ml.webp",
      price: "99",
      cross: "110",
      stars: 4.4,
      off: 5,
      review: "9,742",
      type: "Beauty",
    },

    // Health-Care

    {
      id: "137",
      companyname: "",
      name: "HEALTHKART HK Vitals Skin Radiance Collagen Supplement with Biotin, Orange  (2 x 200 g)",
      image:
        "https://i.postimg.cc/tRPrT3Y5/HEALTHKART-HK-Vitals-Skin-Radiance-Collagen-Supplement-with-Biotin-Orange-2-x-200-g.webp",
      price: "1,499",
      cross: "2,198",
      stars: 4,
      off: 31,
      review: "1,173",
      type: "Health-Care",
      dis: "",
    },
    {
      id: "138",
      companyname: "",
      name: "GNC Triple Strength Fish Oil - 1500 mg with 900 mg of EPA/DHA Omega 3s  (60 No)",
      image:
        "https://i.postimg.cc/L8R473Z0/GNC-Triple-Strength-Fish-Oil-1500-mg-with.webp",
      price: "829",
      cross: "1,586",
      stars: 4.3,
      off: 48,
      review: "913",
      type: "Health-Care",
      dis: "A good dietary supplement does wonders for your body and mind, and is essential in today's hectic lifestyle. But what is that one all-round supplement to help with overall health of the entire family? It's this GOLDEN PILL OF WELLNESS. GNC Triple Strength Fish Oil (30 Softgels) contains thrice the amount of super-absorbable EPA and DHA (900mg) for letting your body take up omega 3s in the most efficient way possible. Extracted from deep-ocean fishes, this clinical-grade formulation is further processed to offer a pure concentrate free from mercury, lead, and other potentially harmful contaminants. It helps keep your heart and eyes healthy, may improve your mental focus and concentration, hydrates your skin for a glowing complexion, and promotes better joint functioning by supporting anti-inflammatory response. Each fish oil capsule is covered in an enteric coating to save you from those unpleasant fishy burps. ",
    },
    {
      id: "139",
      companyname: "",
      name: "MUSCLEBLAZE Creatine Monohydrate, Labdoor USA Certified Creatine  (100 g, Unflavored)",
      image:
        "https://i.postimg.cc/DfLWmgLB/MUSCLEBLAZE-Creatine-Monohydrate-Labdoor-USA-Certified-Creatine-100-g-Unflavored.webp",
      price: "499",
      cross: "899",
      stars: 4.2,
      off: 44,
      review: "1.27,043",
      type: "Health-Care",
      dis: "MuscleBlaze brings to you the Micronized Creatine Monohydrate – a pure, unadulterated, creatine monohydrate that absorbs instantly into your body to give a continuous supply of energy to your muscles during intense activities",
    },
    {
      id: "140",
      companyname: "",
      name: "Dabur Chyawanprash Awaleha | 3X Immunity | Clinically Tested | 2 Kg",
      image: "https://i.postimg.cc/4yTK4738/Dabur-Chyawanprash-Awaleha.webp",
      price: "630",
      cross: "750",
      stars: 4.4,
      off: 16,
      review: "1,41,543",
      type: "Health-Care",
      dis: "",
    },
    {
      id: "141",
      companyname: "",
      name: "Purna Gummies Biotin Cranberry Flavour Gummy for Hair, Nails, & Skin, 1 daily  (30 No)",
      image:
        "https://i.postimg.cc/W4NcV2jM/Purna-Gummies-Biotin-Cranberry-Flavour-Gummy-for-Hair-Nails-Skin-1-daily-30-No.webp",
      price: "99",
      cross: "499",
      stars: 4.1,
      off: 80,
      review: "22,743",
      type: "Health-Care",
      dis: "Biotin is a powerful B-vitamin, supports in fatty acid production, which jump-starts sustainable hair and nail growth and skin regeneration. Purna Biotin Gummies are vegan friendly, shelf life stable and convenient. Biotin supports in cell growth. Cells grow at a consistent rate if the body is functioning with the right nutrients. As we age, our cell proliferation and metabolism decreases due to stress, diet, and exercise. An increased amount of Biotin that the body’s cells receive helps hair growth. When supplementing with Purna Biotin Gummies in the body, you can expect cell proliferation to increase and see healthier hair, skin, and nails",
    },
    {
      id: "142",
      companyname: "",
      name: "Dr. Ortho Relief- Ayurvedic Joint Pain Massage Oil Liquid  (120 ml)",
      image:
        "https://i.postimg.cc/dtCB9Xpd/Dr-Ortho-Relief-Ayurvedic-Joint-Pain-Massage-Oil-Liquid-120-ml.webp",
      price: "265",
      cross: "295",
      stars: 4.2,
      off: 10,
      review: "42,943",
      type: "Health-Care",
      dis: "Dr. Ortho oil is an ayurvedic formulation blended with oil from 8 efficacious medicinal plants. These therapeutic properties of medicinal herbal oils helps in relieving pain associated with muscles and joint pains of neck, shoulder, legs and back. Based on holistic approach, this ayurvedic formulation aids in diminishing various pain without any side effects.",
    },
  ]);

  return (
    <>
      <Storedata.Provider value={[data, setdata]}>
        {props.children}
      </Storedata.Provider>
    </>
  );
}

export default Store;
